require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
pod 'Firebase/Analytics'
target 'notiMark3' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'notiMark3Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
end

target 'notiMark3-tvOS' do
  # Pods for notiMark3-tvOS

  target 'notiMark3-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
